id: AD22D4B86
title: Windhorse Practice of Tārā
type: translation
pechas:
- I300B7377
- I11175835
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:27:18.623221
  last_modified_at: 2023-01-04 11:27:18.623235
  collections:
  - Adeu Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I300B7377/1318: D86B
  I11175835/D8C7: D86B
